version = 0.1
[default.deploy.parameters]
stack_name = "chatbot-backend"
resolve_s3 = true
s3_prefix = "chatbot-backend"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
