AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 10
    Runtime: provided.al2
   
    MemorySize: 128
Resources:
  AIChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AIChatHandler
      Handler: bootstrap
      CodeUri: ./components/AIChat
      Events:
        ChatRoute:
          Type: Api
          Properties:
            Path: /api/AIchat/{proxy+}
            Method: ANY
      Environment:
        Variables:
          DYNAMODB_TABLE: ChatMessagesTable
  ChatTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ChatMessagesTable
      AttributeDefinitions:
        - AttributeName: conversationId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: conversationId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
